services: 
  library:
    container_name: lib
    build: . 
    # image: dockerpezu/library:0.0.1
    ports:
      - 8080:8080
    networks:
      - mynet
  counter:
    container_name: cnt
    image: dockerpezu/counter:0.0.1
    environment: 
      - PORT=8081
      - REDIS_URL=redis://storage
    working_dir: /app
    volumes:
      - ./src:/src
    depends_on:
      - storage
    networks:
      - mynet
  storage:
    image: redis
    volumes:
      - ./data:/data
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default

      
  