services: 
  library:
    container_name: lib
    build: . 
    # image: dockerpezu/library:0.0.1
    ports:
      - 5001:5001
    restart: always
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment: 
      - PORT=5001
      - COUNTER_URL=http://cnt:5002/counter/
      - URL_DB=mongodb://mongo:27017/libraryDB
    networks:
      - mynet
  counter:
    container_name: cnt
    image: dockerpezu/counter:0.0.1
    environment: 
      - PORT=5002
      - REDIS_URL=redis://storage
    working_dir: /app
    volumes:
      - ./src:/src
    depends_on:
      - storage
      - mongo
      - mongo_express
    networks:
      - mynet
  storage:
    image: redis
    volumes:
      - ./redis/data:/data
    networks:
      - mynet

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_DATABASE=db
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - mynet
        
  mongo_express:
    container_name: mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default