services: 
  counter:
    image: dockerpezu/counter:0.0.1
    environment: 
      - PORT=5002
      - REDIS_URL=redis://storage
    ports:
      - 5002:5002
    working_dir: /app
    depends_on:
      - storage

  storage:
    image: redis
    volumes:
      - ./redis/data:/data

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_DATABASE=db
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data/db 

  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example


